routes/web.php
<?php

use Illuminate\Support\Facades\Redirect;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

//Auth::routes();
Route::middleware(['auth'])->namespace('Backend')->prefix('admin')->group(function () {
    Route::get('dashboard', 'DashboardController@index');
    Route::get('users/{id}/suspend', 'UsersController@suspend')->name('users.suspend');
    Route::get('users/{id}/resume', 'UsersController@resume')->name('users.resume');
    Route::resource('users', 'UsersController');
    Route::get('companies/{id}/users', 'CompaniesController@users')->name('companies.users');
    Route::get('companies/{company_id}/invoices', 'InvoicesController@index')->name('companies.invoices');
    Route::get('companies/{company_id}/subscription', 'CompaniesController@editSubscription')->name('companies.subscription');
    Route::post('companies/{company_id}/subscription', 'CompaniesController@updateSubscription')->name('companies.subscription');
    Route::get('companies/{company_id}/invoices/{id}', 'InvoicesController@show')->name('companies.invoices.show');
    Route::get('companies/{company_id}/invoices/{id}/download', 'InvoicesController@download')->name('companies.invoices.download');
    Route::resource('companies', 'CompaniesController');
    Route::resource('plans', 'PlansController');
    Route::resource('coupons', 'CouponsController');
    Route::resource('standard/forms', 'StandardFormsController');
    Route::resource('standard/scopes', 'StandardScopesController');
    Route::get('standard/moisture', 'StandardMoistureMapController@index')->name('moisture-page');
    Route::get('standard/area', 'StandardAffectedAreasController@areaPage')->name('areas-page');
    Route::get('standard/team', 'StandardTeamsController@teamsPage')->name('teams-page');
    Route::resource('units-of-measure', 'UnitsOfMeasureController');
    Route::get('notifications/auto-responders/{id}/preview', 'AutoRespondersController@preview')->name('auto-responders.preview');
    Route::resource('notifications/auto-responders', 'AutoRespondersController');

// ------------------API-----------------//
    Route::resource('standard/areas', 'StandardAffectedAreasController');
    Route::resource('standard/teams', 'StandardTeamsController');
    Route::resource('standard/structure', 'StardardMoistureMapStructureController');
    Route::resource('standard/material', 'StardardMoistureMapMaterialController');
    Route::get('uoms/jsonResult', 'UnitsOfMeasureController@jsonResult');
    Route::get('standard-scopes/form', 'StandardScopesController@form');
    Route::post('standard-scopes/form-update', 'StandardScopesController@formUpdate');
    Route::get('standard-moisture/form', 'StandardMoistureMapController@form');
    Route::post('standard-moisture/form-update', 'StandardMoistureMapController@formUpdate');
    Route::get('standard-areas/form', 'StandardAffectedAreasController@form');
    Route::post('standard-areas/form-update', 'StandardAffectedAreasController@formUpdate');

    Route::resource('training/categories', 'TrainingController');
    Route::resource('training/videos', 'TrainingVideosController');

    Route::get('ticket/{ticket_id}', 'TicketsController@show');
    Route::post('comment_ticket', 'TicketCommentsController@store');
    Route::get('tickets/list', 'TicketsController@index');
    Route::post('close_ticket/{ticket_id}', 'TicketsController@close');
    Route::resource('ticket_categories', 'TicketCategoriesController');
});

Route::get('/project/print/{id}', 'Api\ProjectFormsController@print');
Route::get('/form/preview/{token}', 'Api\StandardsController@preview');
Route::get('/dropbox-auth', 'Api\CompaniesController@dropboxAuth');
Route::post('/dropbox-auth', 'Api\CompaniesController@storeDropboxAuth');

Route::middleware([])->namespace('Frontend')->group(function () {
    Route::get('/panel', ['uses' => 'HomeController@index', 'as' => 'main.index']);
});


Route::namespace('Marketing')->group(function () {
    Route::get('/', 'HomeController@index');
    Route::get('/about', 'AboutController@index');
    Route::get('/features', 'FeatureController@index');
    Route::get('/terms-and-conditions', 'LegalDocumentController@showTermsAndConditions');
    Route::get('/privacy-policy', 'LegalDocumentController@showPrivacyPolicy');

    Route::group(['prefix' => 'contact-us'], function () {
        Route::get('/', 'ContactUsController@index');
        Route::post('/', 'ContactUsController@store');
    });

    Route::group(['prefix' => MAILING_LIST_PATH], function () {
        Route::get('/', 'MailingListController@index');
        Route::post('/', 'MailingListController@store');
        Route::post('/verify', 'MailingListController@verify');
        Route::get('/confirm-cancellation/{cancellationKey}', 'MailingListController@confirmRemoval');
        Route::get('/confirm/{confirmationKey}', 'MailingListController@confirm');
    });

    Route::get(MAILING_LIST_CANCEL_PATH, ['uses' => 'MailingListController@cancel', 'as' => 'mailing-list.cancel']);

    Route::group(['prefix' => 'blog'], function () {
        Route::get('/', 'BlogController@index');
        Route::get('/article/{id}/{slug}', ['uses' => 'ArticleController@index', 'as' => ARTICLE_ROUTE_NAME]);
    });

    Route::get('/faq', 'FAQController@index');
});

Route::middleware(['auth'])->namespace('Marketing\CMS')->group(function () {
    Route::group(['prefix' => 'cms'], function () {
        Route::get('/', function () {
            return redirect(route('cms.contact-people'));
        });
        Route::group(['prefix' => 'contact-people'], function () {
            Route::get('/', ['uses' => 'ContactPersonController@index', 'as' => 'cms.contact-people']);
            Route::delete('/delete/{id}', ['uses' => 'ContactPersonController@destroy', 'as' => 'cms.faq.destroy']);
        });

        Route::group(['prefix' => 'mailing-list'], function () {
            Route::get('/', 'MailingListController@index');
            Route::get('/download-csv', 'MailingListController@downloadCSV');
            Route::delete('/delete/{id}', 'MailingListController@destroy');
        });

        Route::group(['prefix' => 'other-settings'], function () {
            Route::get('/', ['uses' => 'MarketingSettingController@index', 'as' => 'cms.other-settings']);
            Route::get('/edit', 'MarketingSettingController@edit');
            Route::post('/edit', 'MarketingSettingController@update');
        });

        Route::group(['prefix' => 'faq'], function () {
            Route::get('/', 'FAQController@index');
            Route::get('/create', ['uses' => 'FAQController@create', 'as' => 'cms.faq.create']);
            Route::post('/', ['uses' => 'FAQController@store', 'as' => 'cms.faq.store']);
            Route::get('/edit/{id}', ['uses' => 'FAQController@edit', 'as' => 'cms.faq.edit']);
            Route::put('/{id}', ['uses' => 'FAQController@update', 'as' => 'cms.faq.update']);
            Route::delete('/delete/{id}', ['uses' => 'FAQController@destroy', 'as' => 'cms.faq.destroy']);
        });

        Route::group(['prefix' => 'country'], function () {
            Route::get('/', 'SupportedCountryController@index');
            Route::get('/create', ['uses' => 'SupportedCountryController@create', 'as' => 'cms.country.create']);
            Route::post('/', ['uses' => 'SupportedCountryController@store', 'as' => 'cms.country.store']);
            Route::get('/edit/{id}', ['uses' => 'SupportedCountryController@edit', 'as' => 'cms.country.edit']);
            Route::put('/{id}', ['uses' => 'SupportedCountryController@update', 'as' => 'cms.country.update']);
            Route::delete('/delete/{id}', ['uses' => 'SupportedCountryController@destroy', 'as' => 'cms.country.destroy']);
        });

        Route::group(['prefix' => 'blog-article'], function () {
            Route::get('/', 'ArticleController@index');
            Route::get('/edit/{id}', ['uses' => 'ArticleController@edit', 'as' => 'cms.blog-article.edit']);
            Route::put('/{id}', ['uses' => 'ArticleController@update', 'as' => 'cms.blog-article.update']);
            Route::get('/{id}/{slug}', ['uses' => 'ArticleController@show', 'as' => 'cms.blog-article.show']);
            Route::get('/create', ['uses' => 'ArticleController@create', 'as' => 'cms.blog-article.create']);
            Route::post('/', ['uses' => 'ArticleController@store', 'as' => 'cms.blog-article.store']);
            Route::delete('/delete/{id}', ['uses' => 'ArticleController@destroy', 'as' => 'cms.blog-article.destroy']);
        });

        Route::group(['prefix' => 'legal-documents'], function () {
            Route::get('/', 'LegalDocumentController@index');
            Route::get('/{type}', 'LegalDocumentController@show');
            Route::get('/edit/{type}', ['uses' => 'LegalDocumentController@edit', 'as' => 'cms.legal-document.edit']);
            Route::put('/', ['uses' => 'LegalDocumentController@update', 'as' => 'cms.legal-document.update']);
        });
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Backpack\CRUD\CrudTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Cashier\Billable;
use Stripe\Customer;
use Stripe\Subscription;
use Tymon\JWTAuth\Contracts\JWTSubject;

/**
 * @property string email
 * @property string stripe_id
 * @property Customer customer
 * @property string card_expiry
 * @property string card_brand
 * @property string card_last_four
 * @property Subscription subscription
 * @property string trial_ends_at
 */
class User extends Authenticatable implements JWTSubject
{
    use Notifiable, Billable, CrudTrait, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'address',
        'city',
        'state',
        'zip',
        'phone',
        'email',
        'password',
        'role_id',
        'company_id',
        'verified',
        'card_expiry',
        'card_brand',
        'card_last_four',
        'trial_ends_at',
        'password_set_token',
        'timezone',
        'status',
        'coupon'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $visible = [
        'id',
        'first_name',
        'last_name',
        'address',
        'city',
        'state',
        'zip',
        'phone',
        'email',
        'password',
        'company_id',
        'role_id',
        'verified',
        'trial_ends_at',
        'stripe_is_assigned',
        'full_name',
        'timezone',
        'status',
        'coupon',

        'company',
        'role',
        'teams'
    ];

    /**
     * @var array
     */
    protected $appends = [
        'stripe_is_assigned',
        'full_name',
    ];

    public function setTrialEndsAtAttribute($value)
    {
        $this->attributes['trial_ends_at'] = $value ? Carbon::createFromTimestamp($value)->toDateTimeString() : null;
    }

    /**
     * Relation with companies.
     */
    public function company()
    {
        return $this->belongsTo(Company::class, 'company_id');
    }


    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function teams()
    {
        return $this->belongsToMany(Team::class, 'users_teams');
    }

    /**
     * @param string $value
     *
     * @return string
     */
    public function getCreatedAtAttribute($value)
    {
        return date("m/d/Y H:m", strtotime($value));
    }

    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }

    /**
     * @param string $role
     *
     * @return bool
     */
    public function hasRole(string $role): bool
    {
        return strtolower($this->role->name) === strtolower($role);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function ticketComments()
    {
        return $this->hasMany(TicketComment::class, 'user_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function tickets()
    {
        return $this->hasMany(Ticket::class);
    }

    /**
     * @return Customer
     */
    public function getCustomerAttribute()
    {
        if (!$this->stripe_id) {
            return null;
        }

        return Customer::retrieve($this->stripe_id);
    }

    /**
     * @return bool
     */
    public function getStripeIsAssignedAttribute()
    {
        return !empty($this->stripe_id);
    }

    /**
     * @return Subscription|null
     */
    public function getSubscriptionAttribute()
    {
        if (!$this->stripe_id) {
            return null;
        }

        $subscriptions = Subscription::all(['status' => 'all', 'customer' => $this->stripe_id]);

        return count($subscriptions->data) ? $subscriptions->data[0] : null;
    }

    /**
     * @return bool
     */
    public function isSubscribed()
    {
        $subscription = $this->subscription;

        return $subscription &&
            ($subscription->status === 'active' || ($subscription->status === 'trialing' && $this->isOnTrial()));
    }

    /**
     * @return bool
     */
    public function isOnTrial()
    {
        if (!$this->trial_ends_at) {
            return false;
        }

        $currentDate = Carbon::now();
        $trialEndsAt = Carbon::createFromFormat('Y-m-d H:i:s', $this->trial_ends_at);

        return $currentDate->diffInHours($trialEndsAt, false) > 0;
    }

    /**
     * @return string
     */
    public function getFullNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }
}

app/Http/Controllers/Api/DashboardController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Requests\Dashboard\DashboardEquipmentRequest;
use App\Http\Requests\Dashboard\DashboardProjectsRequest;
use App\Models\Category;
use App\Models\Project;
use App\Models\Status;
use Illuminate\Database\Connection;

class DashboardController extends ApiController
{
    /**
     * @var Project
     */
    private $project;

    /**
     * @var Connection
     */
    private $db;

    /**
     * @var Category
     */
    private $category;

    /**
     * DashboardController constructor.
     * @param Project $project
     * @param Connection $db
     * @param Category $category
     */
    public function __construct(Project $project, Connection $db, Category $category)
    {
        $this->project = $project;
        $this->db = $db;
        $this->category = $category;
    }

    /**
     * @param DashboardProjectsRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function projects(DashboardProjectsRequest $request)
    {
        $year = $request->get('year');
        $team = $request->get('team');

        $projects = $this->project->where('created_at', 'like', "%{$year}%")
            ->where('assigned_to', $team)
            ->groupBy('status')
            ->get([$this->db->raw('count(id) as total'), 'status']);

        $data = ['all' => 0];
        foreach ($projects as $project) {
            $data[snake_case($project->status_info->name)] = $project->total;
            $data['all'] += $project->total;
        }

        return $this->respond(['data' => $data]);
    }

    /**
     * @param DashboardEquipmentRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function equipment(DashboardEquipmentRequest $request)
    {
        $data = [];
        $team = $request->get('team');
        $categories = $this->category->with('equipments')->orderBy('name', 'asc')->get();

        foreach ($categories as $category) {
            $data[] = [
                'name' => $category->name,
                'available' => $this->fetchEquipmentQuantityByStatusAndTeam($team, Status::AVAILABLE, $category),
                'set' => $this->fetchEquipmentQuantityByStatusAndTeam($team, Status::SET, $category),
                'loan' => $this->fetchEquipmentQuantityByStatusAndTeam($team, Status::LOAN, $category),
                'missing' => $this->fetchEquipmentQuantityByStatusAndTeam($team, Status::MISSING, $category),
                'ooc' => $this->fetchEquipmentQuantityByStatusAndTeam($team, Status::OOC, $category),
                'total' => $category->equipments()->where('team_id', '=', $team)->count()
            ];
        }

        return $this->respond(['data' => $data]);
    }

    /**
     * @param int $teamId
     * @param int $statusId
     * @param Category $category
     * @return int
     */
    private function fetchEquipmentQuantityByStatusAndTeam(int $teamId, int $statusId, Category $category)
    {
        return $category->equipments()
            ->where('team_id', '=', $teamId)
            ->where('status_id', '=', $statusId)
            ->count();
    }
}

resources/views/dashboard/companies/form.blade.php
@extends('backpack::layout')

@section('header')
    <section class="content-header">
        <h1>
            User
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url(config('backpack.base.route_prefix', 'admin')) }}">{{ config('backpack.base.project_name') }}</a></li>
            <li><a href="{{ route('companies.index') }}">Companies</a></li>
            <li class="active">Edit Company</li>
        </ol>
    </section>
@endsection


@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <a href="{{ route('companies.index') }}"><i class="fa fa-angle-double-left"></i> Back to companies</a>
            <br>
            <br>
            <div class="box box-default">
                <div class="box-header with-border">
                    <div class="box-title">Edit Company</div>
                </div>

                <div class="box-body">
                    <form method="post"
                          action="{{ route('companies.update', $company->id) }}" enctype="multipart/form-data">
                        <input type="hidden" name="_method" value="patch">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" class="form-control" name="name" value="{{ $company->name }}">
                            @if($errors->has('name'))
                                <span class="text-danger">{{ $errors->first('name') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Logo</label>
                            <input type="file" class="form-control" name="logo">
                            @if($errors->has('logo'))
                                <span class="text-danger">{{ $errors->first('logo') }}</span>
                            @endif
                        </div>
                        @if($company->public_logo_path)
                        <div class="form-group">
                            <img src="{{ asset($company->public_logo_path) }}">
                        </div>
                        @endif
                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-sm btn-primary">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/companies/index.blade.php
@extends('backpack::layout')

@section('header')
    <style>
        th > a {
            cursor: pointer;
        }
    </style>
    <section class="content-header">
        <h1>
            Companies
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url(config('backpack.base.route_prefix', 'admin')) }}">{{ config('backpack.base.project_name') }}</a></li>
            <li class="active">Companies</li>
        </ol>
    </section>
@endsection


@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="box box-default">
                <div class="box-header with-border">
                    <div class="box-title">Companies ({{ $companies->total() }})</div>
                </div>

                <div class="box-header">
                    <form method="get" id="filters" class="form-inline" action="{{ route('companies.index') }}">
                        <div class="form-group form-group-sm">
                            <label>Subscription status: </label>
                            <select class="form-control form-control-sm" name="status">
                                <option value="all" @if(request('status') === 'all') selected @endif>All</option>
                                <option value="active" @if(request('status') === 'active') selected @endif>Active</option>
                                <option value="canceled" @if(request('status') === 'canceled') selected @endif>Cancelled</option>
                                <option value="past_due" @if(request('status') === 'past_due') selected @endif>Past Due</option>
                                <option value="trialing" @if(request('status') === 'trialing') selected @endif>Trialing</option>
                                <option value="unpaid" @if(request('status') === 'unpaid') selected @endif>Unpaid</option>
                            </select>
                        </div>
                        <div class="form-group form-group-sm">
                            <label>Name: </label>
                            <input type="text" class="form-control form-control-sm" name="name" value="{{ request('name') }}">
                        </div>
                        <div class="form-group form-group-sm">
                            <label>Email: </label>
                            <input type="text" class="form-control form-control-sm" name="email" value="{{ request('email') }}">
                        </div>
                        <div class="form-group form-group-sm">
                            <label>Coupon: </label>
                            <input type="text" class="form-control form-control-sm" name="coupon" value="{{ request('coupon') }}">
                        </div>

                        <input type="hidden" name="sort" value="{{ request('sort') }}">

                        <div class="form-group form-group-sm pull-right" style="margin-left: 15px;">
                            <button class="btn btn-sm btn-primary"><i class="fa fa-search"></i> Search</button>
                        </div>
                        <div class="form-group form-group-sm pull-right">
                            <a class="btn btn-sm btn-warning" href="{{ route('companies.index') }}"><i class="fa fa-filter"></i> Clear</a>
                        </div>
                    </form>
                </div>

                <div class="box-body">
                    <table class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th><a id="sort"><strong>Company</strong></a></th>
                            <th>Address</th>
                            <th>Coupon</th>
                            <th>Company Email</th>
                            <th>Main Registered Email</th>
                            <th>Date Account Created</th>
                            <th>Date Next Payment Due</th>
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($companies as $company)
                            <tr>
                                <td>{{ $company->name }}</td>
                                <td>{{ $company->full_address }}</td>
                                <td>{{ optional($company->user)->coupon ?? '-' }}</td>
                                <td>{{ $company->email }}</td>
                                <td>{{ optional($company->user)->email }}</td>
                                <td>{{ optional($company->user)->created_at }}</td>
                                <td>{{ optional($company->user)->subscription ? \Carbon\Carbon::createFromTimestamp($company->user->subscription->current_period_end)->format('m/d/Y H:m') : 'n/a' }}</td>
                                <td>{{ optional($company->user)->subscription ? ucfirst($company->user->subscription->status) : 'n/a' }}</td>
                                <td class="text-center">
                                    <a class="btn btn-xs btn-primary" href="{{ route('companies.users', $company->id) }}">
                                        <i class="fa fa-users"></i> Users
                                    </a>
                                    <a class="btn btn-xs btn-primary" href="{{ route('companies.invoices', $company->id) }}">
                                        <i class="fa fa-archive"></i> Invoices
                                    </a>
                                    @if(isset($company->user) && $company->user->stripe_id && optional($company->user->subscription)->status !== 'canceled')
                                        <a class="btn btn-xs btn-warning" href="{{ route('companies.subscription', $company->id) }}">
                                            <i class="fa fa-credit-card"></i> Subscription
                                        </a>
                                    @endif
                                    <a class="btn btn-xs btn-default" href="{{ route('companies.edit', $company->id) }}">
                                        <i class="fa fa-edit"></i> Edit
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                {{ $companies->links() }}
            </div>
        </div>
    </div>
@endsection

@section('after_scripts')
    <script>
        $(document).ready(function() {
            $('#sort').on('click', function() {
                let currentSort = $('[name="sort"]').val();
                console.log(currentSort)
                if (currentSort === '' || currentSort === 'desc') {
                    $('[name="sort"]').attr('value', 'asc')
                } else {
                    $('[name="sort"]').attr('value', 'desc')
                }

                $('#filters').submit()
            })
        })
    </script>
@endsection

resources/views/dashboard/companies/subscription.blade.php
@extends('backpack::layout')

@section('header')
    <section class="content-header">
        <h1>
            Company Subscription
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url(config('backpack.base.route_prefix', 'admin')) }}">{{ config('backpack.base.project_name') }}</a></li>
            <li class="active">Edit {{ $company->name }} Subscription</li>
        </ol>
    </section>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <a href="{{ route('companies.index') }}"><i class="fa fa-angle-double-left"></i> Back to companies</a>
            <br>
            <br>
            @if(isset($company->user) && $company->user->stripe_id)
                <div class="box box-default">
                    <div class="box-header with-border">
                        <div class="box-title">{{ $company->name }} Subscription Details</div>
                    </div>

                    <div class="box-body">
                        <form method="post" action="{{ route('companies.subscription', $company->id) }}">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label>Action</label>
                                <select class="form-control" name="action">
                                    <option value="">-- Please select --</option>
                                    <option value="terminate_at_the_end">Terminate subscription at period end</option>
                                    <option value="terminate_now">Terminate subscription now</option>
                                </select>
                                @if($errors->has('action'))
                                    <span class="text-danger">{{ $errors->first('action') }}</span>
                                @endif
                            </div>
                            <!-- //TODO future improvement -->
                            {{--<div class="form-group">--}}
                                {{--<label>Days</label>--}}
                                {{--<input type="number" min="1" class="form-control" name="days" value="1">--}}
                                {{--@if($errors->has('days'))--}}
                                    {{--<span class="text-danger">{{ $errors->first('days') }}</span>--}}
                                {{--@endif--}}
                            {{--</div>--}}
                            <div class="form-group text-center">
                                <button type="submit" class="btn btn-sm btn-danger">Apply</button>
                            </div>
                        </form>
                    </div>
                </div>
            @endif

        </div>
    </div>
@endsection